### ISSUE TITLE
The local %pop-argument function can be ignored

### ISSUE THREAD

**Issue by alessiostalla** [40ants/defmain#6]
SBCL reports:
```
; note: deleting unused function
;   (FLET DEFMAIN::%POP-ARGUMENT :IN ...)
```

`(declare (ignorable #'%pop-argument))` would fix that.

**Comment by svetlyak40wt** [comment]
Oh, I didn't know `declare ignorable` works with local functions!

Fixed in https://github.com/40ants/defmain/pull/7

**Comment by alessiostalla** [comment]
That was quick, thanks! :)

**Comment by svetlyak40wt** [comment]
You welcome!

**Comment by svetlyak40wt** [comment]
Install the latest version from https://ultralisp.org/ it should appear there soon.

(Usually, new updates are included into the dist in a few minutes, but I discovered, the queue of project checks is stuck and now Ultralisp slowly rechecks a thousand libraries for updates).
